### ISSUE TITLE
kernel_require.rb:92:in `require'

### ISSUE THREAD

**Issue by alexandergz1983** [evolbeginner/iSeeCE#1]
Regards.

I am trying to run your program, however I run into the following problem when running it:

/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- Dir (LoadError)

Could this be a problem with the version of ruby that I implement or what is the problem. I can't find a solution.

Thank you.

**Comment by evolbeginner** [comment]
Hi Alexander,

Thanks for your interest in iSeeCE. The reason is because the environmental variable RUBYLIB, which specifies where to look for libraries for Ruby, is incorrectly set in iSeeCE. I have added a single line to the wrapper script iSeeCE (L14), and it should normally work now. My apologizes for the bug. Please do not hesitate to let me know should there be any questions.

**Comment by alexandergz1983** [comment]
Regards.

fix part of the problem by changing require to require_relative with its corresponding path. However, now I have the following problem:


Traceback (most recent call last):
	3: from /scratch/mauve_pro/iSeeCE/selectOrthoFromMauveOrthomcl.rb:208:in `<main>'
	2: from /scratch/mauve_pro/iSeeCE/selectOrthoFromMauveOrthomcl.rb:52:in `get_orthomcl'
	1: from /scratch/mauve_pro/iSeeCE/selectOrthoFromMauveOrthomcl.rb:52:in `open'
/scratch/mauve_pro/iSeeCE/selectOrthoFromMauveOrthomcl.rb:52:in `initialize': No such file or directory @ rb_sysopen - OrthoMCL/mclOutput1.5 (Errno::ENOENT)
#################                                                         25.00%Traceback (most recent call last):


Sorry for the disturbances.

Thanks for your help.

**Comment by evolbeginner** [comment]
Hi Alex,

Apologizes for the first issue. It should be $CWD/lib in L14 of iSeeCE.sh. It's been changed in the iSeeCE.sh now. In this way, there will be no need to change "require" to "require_relative" in certain scripts.
![image](https://user-images.githubusercontent.com/8715751/93341869-3735a480-f861-11ea-8aa6-8422f90e3525.png)


For the second issue, may I ask whether you have outputs in the folder OrthoMCL? Mine is as follows, where there are mclOutput files with the inflation factor 1.5, 2, 4, and 6.
![image](https://user-images.githubusercontent.com/8715751/93341686-005f8e80-f861-11ea-9823-d3a797e64f86.png)

Thanks.

**Comment by alexandergz1983** [comment]
I don't get those kinds of results. 
Only similarSequence with 0 bytes and complianFasta folder if it generates a file with data.

**Comment by evolbeginner** [comment]
Seems to me to be related to orthomcl. Have you tried "bash check_requirements.sh"? If OrthoMCL is correctly installed and detected by iSeeCE, it should give you the following image:
![image](https://user-images.githubusercontent.com/8715751/93348731-2d17a400-f869-11ea-9910-3fd1aa81171e.png)

Thanks.

**Comment by alexandergz1983** [comment]
I already did it and everything is ok.

**Comment by evolbeginner** [comment]
So the paths to orthomcl_config_file and install_schema_log_file in the file **scripts/run_orthomcl.sh** have been changed to the paths in your computer, right? 
![image](https://user-images.githubusercontent.com/8715751/93350258-05294000-f86b-11ea-8629-a4d174ee5149.png)

If not, "`bash check_requirements.sh`" should give you something like 
![image](https://user-images.githubusercontent.com/8715751/93350590-6224f600-f86b-11ea-81c8-1a63570e2367.png).

Thanks.

**Comment by evolbeginner** [comment]
Hi Alex,

I guess it could be due to the setting of the account of MySQL. The default one is root (specified by "-uroot" in L16 of scripts/run_orthomcl.sh) and no password is provided. However, it may not be your case. I will be providing the option to change it soon. Meanwhile, you may wish to change "root_argu" and "passwd_argu" in L188 of the script scripts/run_orthomcl.sh directly. I am very sorry for this problem and any inconvenience it caused.
![image](https://user-images.githubusercontent.com/8715751/93352020-f8a5e700-f86c-11ea-904d-ce36c10a2ac5.png)

for example
` root_argu="-uroot"; password_argu="-p123"`

**Comment by alexandergz1983** [comment]
Hi,

Try the following changes:
1) check everything again
![1edit](https://user-images.githubusercontent.com/18590334/93457051-d2209400-f8de-11ea-89dd-e13228a5f8fd.png)

2) Change mysql -u root -e to mysql -u root -p, to check access to mysql.

![2edit](https://user-images.githubusercontent.com/18590334/93457316-19a72000-f8df-11ea-8e4c-670b4165c500.png)

3)Change L52 in selectOrthoFromMauveOrthomcl.rb:

in_fh = orthomcl_file == '-'? STDIN: File.open (orthomcl_file, 'r') by in_fh = orthomcl_file == '-'? STDIN: File.open (orthomcl_file, 'w') and curiously if it creates the "Outmcl" but without data.

I really don't understand what the error is. :(

#######################################################

change "root_argu" and "passwd_argu" in L188 of the script scripts/run_orthomcl.sh directly???...

**Comment by evolbeginner** [comment]
Could you please change "`mysql -u root -e to mysql -u root -p`" to "`mysql -uUSERNAME -pPASSWORD -e 'drop database orthomcl; create database orthomcl;'`"? I think the problem is because mysql was not correctly accessed.

**Comment by alexandergz1983** [comment]
Hello,

I am testing iSeeCe on my laptop and not on the server to try and find the problem. In my laptop I have progressed more, however now I get the following:


/home/bio200/programas/iSeeCE/iSeeCE.sh --indir /home/bio200/programas/iSeeCE/test/ --outdir /home/bio200/programas/iSeeCE/results1 -b 0.9 --gc_count_min 3 --ortho_count_min --is_mauve  --mauve /home/bio200/programas/mauve/linux-x64/progressiveMauve --mauve_jar /home/bio200/programas/mauve/Mauve.jar
Parsing Genbank files ......
given is experimental at /home/bio200/programas/iSeeCE/scripts/gff2fasta.pl line 265.
when is experimental at /home/bio200/programas/iSeeCE/scripts/gff2fasta.pl line 266.
when is experimental at /home/bio200/programas/iSeeCE/scripts/gff2fasta.pl line 274.
##################################                                        50.00%given is experimental at /home/bio200/programas/iSeeCE/scripts/gff2fasta.pl line 265.
when is experimental at /home/bio200/programas/iSeeCE/scripts/gff2fasta.pl line 266.
when is experimental at /home/bio200/programas/iSeeCE/scripts/gff2fasta.pl line 274.
###################################################################       100.00%
Running OrthoMCL (which usually takes a long time) ......
###################################################################       100.00%
Running MAFFT (which usually takes a long time) ......
###################################################################       100.00%
Running FastTree ......

mv: no se puede efectuar `stat' sobre '*tre': No existe el archivo o el directorio
Identitying tandem duplicates ......
Traceback (most recent call last):
  File "/home/bio200/programas/iSeeCE/scripts/get_TD.py", line 241, in <module>
    blast_pairsh = read_blast_files(blast_files, e_value_cutoff, gene_regexp, aln_length_cutoff, identity_cutoff)
  File "/home/bio200/programas/iSeeCE/scripts/get_TD.py", line 60, in read_blast_files
    in_fh = open(blast_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/bio200/programas/iSeeCE/results1/OrthoMCL/all_VS_all.out.tab'
###################################################################       100.00%
Parsing FastTree result ......
ls: no se puede acceder a '/home/bio200/programas/iSeeCE/results1/FastTree/trees/*FastTree.tre': No existe el archivo o el directorio
Runtime error (func=(main), adr=15): Divide by zero
/home/bio200/programas/iSeeCE/scripts/processbar.sh: línea 7: current*barlen/total: división por 0 (el elemento de error es "total")

Traceback (most recent call last):
	2: from /home/bio200/programas/iSeeCE/filterFastTree.rb:51:in `<main>'
	1: from /home/bio200/programas/iSeeCE/filterFastTree.rb:51:in `open'
/home/bio200/programas/iSeeCE/filterFastTree.rb:51:in `initialize': No such file or directory @ rb_sysopen - /home/bio200/programas/iSeeCE/results1/FastTree/trees.FastTree_result (Errno::ENOENT)
Finding potential converted genes by gene synteny based on 
best reciprocal BLAST hits ......
Traceback (most recent call last):
	3: from /home/bio200/programas/iSeeCE/bestHit.rb:221:in `<main>'
	2: from /home/bio200/programas/iSeeCE/bestHit.rb:129:in `read_summary_file'
	1: from /home/bio200/programas/iSeeCE/bestHit.rb:129:in `open'
/home/bio200/programas/iSeeCE/bestHit.rb:129:in `initialize': No such file or directory @ rb_sysopen - ../FastTree/trees.summary (Errno::ENOENT)

Generating final output ......
Traceback (most recent call last):
	2: from /home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `<main>'
	1: from /home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `open'
/home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `initialize': No such file or directory @ rb_sysopen - ../FastTree/GC.raw_result (Errno::ENOENT)
###################################################################       100.00%
Done!

**Comment by alexandergz1983** [comment]
Hello,

I am testing iSeeCe on my laptop and not on the server to try and find the problem. In my laptop I have progressed more, however now I get the following:

done.
root alignment has 274 superintervals
root alignment length: 1749896
Organisms have 34.1% GC
This line could not be parsed:                 seq:cag)
This line could not be parsed:                 seq:tac)
This line could not be parsed:                 seq:tgg)
This line could not be parsed:                 seq:tct)
This line could not be parsed:                 seq:ggt)
This line could not be parsed:                 seq:cat)
This line could not be parsed:                 seq:tac)
This line could not be parsed:                 seq:tgg)
This line could not be parsed:                 seq:ttc)
Running OrthoMCL (which usually takes a long time) ......
###################################################################       100.00%
Running MAFFT (which usually takes a long time) ......
###################################################################       100.00%
Running FastTree ......

mv: no se puede efectuar `stat' sobre '*tre': No existe el archivo o el directorio
Identitying tandem duplicates ......
Traceback (most recent call last):
  File "/home/bio200/programas/iSeeCE/scripts/get_TD.py", line 241, in <module>
    blast_pairsh = read_blast_files(blast_files, e_value_cutoff, gene_regexp, aln_length_cutoff, identity_cutoff)
  File "/home/bio200/programas/iSeeCE/scripts/get_TD.py", line 60, in read_blast_files
    in_fh = open(blast_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/bio200/programas/iSeeCE/results1/OrthoMCL/all_VS_all.out.tab'

###################################################################       100.00%

Parsing FastTree result with Mauve ......
ls: no se puede acceder a '/home/bio200/programas/iSeeCE/results1/FastTree/trees/*': No existe el archivo o el directorio
Runtime error (func=(main), adr=15): Divide by zero
/home/bio200/programas/iSeeCE/scripts/processbar.sh: línea 7: current*barlen/total: división por 0 (el elemento de error es "total")
Finding potential converted genes by gene synteny based on 
best reciprocal BLAST hits ......
Traceback (most recent call last):
	3: from /home/bio200/programas/iSeeCE/bestHit.rb:221:in `<main>'
	2: from /home/bio200/programas/iSeeCE/bestHit.rb:129:in `read_summary_file'
	1: from /home/bio200/programas/iSeeCE/bestHit.rb:129:in `open'
/home/bio200/programas/iSeeCE/bestHit.rb:129:in `initialize': No such file or directory @ rb_sysopen - ../FastTree/trees.summary (Errno::ENOENT)

Generating final output ......
Traceback (most recent call last):
	2: from /home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `<main>'
	1: from /home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `open'
/home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `initialize': No such file or directory @ rb_sysopen - ../FastTree/GC.mauve.raw_result (Errno::ENOENT)
Traceback (most recent call last):
	2: from /home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `<main>'
	1: from /home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `open'
/home/bio200/programas/iSeeCE/getCandidateGC.rb:41:in `initialize': No such file or directory @ rb_sysopen - ../FastTree/GC.raw_result (Errno::ENOENT)
###################################################################       100.00%
Done!

**Comment by evolbeginner** [comment]
Thanks for the feedback.

Here are a few things that you may wish to help to check.

1. Could you please have a look at whether OrthoMCL was correctly run? For example, could you please show me what is inside the folder OrthoMCL. I noted that a warming message says /home/bio200/programas/iSeeCE/results1/OrthoMCL/all_VS_all.out.tab is not accessible.
It should look like
![image](https://user-images.githubusercontent.com/8715751/93608462-39346a80-f9fd-11ea-874d-10393e198082.png)

2. Would you please mind showing me your command to run iSeeCE? I was wondering whether "--mauve" was specified. If so, I would suggest trying to run iSeeCE again without it.

Thanks.

**Comment by evolbeginner** [comment]
Hi Alex,

Sorry I just saw the complete arguments.

Would you please mind trying removing "`--is_mauve --mauve /home/bio200/programas/mauve/linux-x64/progressiveMauve --mauve_jar /home/bio200/programas/mauve/Mauve.jar`"? I think this affects the final parsing of the result. My experience is if your bacterial genomes are not that closely related (say between species, genus or farther) then you can run without Mauve. In such cases, Mauve might be too conservative (and is time consuming).

**Comment by alexandergz1983** [comment]
This is the command without mauve:

iSeeCE.sh --indir test/ --outdir output --gc_count_min 8 --bootstrap 0.9

Parsing Genbank files ......
given is experimental at /scratch/mauve_pro/iSeeCE/scripts/gff2fasta.pl line 265.
when is experimental at /scratch/mauve_pro/iSeeCE/scripts/gff2fasta.pl line 266.
when is experimental at /scratch/mauve_pro/iSeeCE/scripts/gff2fasta.pl line 274.
##################################                                        50.00%given is experimental at /scratch/mauve_pro/iSeeCE/scripts/gff2fasta.pl line 265.
when is experimental at /scratch/mauve_pro/iSeeCE/scripts/gff2fasta.pl line 266.
when is experimental at /scratch/mauve_pro/iSeeCE/scripts/gff2fasta.pl line 274.
###################################################################       100.00%
Running OrthoMCL (which usually takes a long time) ......
###################################################################       100.00%
Running MAFFT (which usually takes a long time) ......
###################################################################       100.00%
Running FastTree ......

mv: no se puede efectuar `stat' sobre '*tre': No existe el fichero o el directorio
Identitying tandem duplicates ......
Traceback (most recent call last):
  File "/scratch/mauve_pro/iSeeCE/scripts/get_TD.py", line 241, in <module>
    blast_pairsh = read_blast_files(blast_files, e_value_cutoff, gene_regexp, aln_length_cutoff, identity_cutoff)
  File "/scratch/mauve_pro/iSeeCE/scripts/get_TD.py", line 60, in read_blast_files
    in_fh = open(blast_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'output/OrthoMCL/all_VS_all.out.tab'

**Comment by alexandergz1983** [comment]
However, it does not generate data in the created files.

alex@alu10:/scratch/mauve_pro/Bordetella_species/resultsiSeeCE/output$ cd OrthoMCL/
alex@alu10:/scratch/mauve_pro/Bordetella_species/resultsiSeeCE/output/OrthoMCL$  du -cs * | sort -nr
1028	total
1024	compliantFasta
4	orthomcl_pairs.log
0	similarSequences.txt
0	pairs
0	mclOutput6
0	mclOutput4
0	mclOutput2
0	mclOutput1.5
0	mclOutput
0	mclInput
0	groups.txt

**Comment by evolbeginner** [comment]
Hi Alex,

I think I found where the problem is rooted: the configuration file for OrthoMCL was not changed according to your path in the original script (scripts/run_orthomcl.sh). I am very sorry for this error.

I have updated iSeeCE to v1.1, which includes a `orthomcl.config` file. **You may need to edit the password and login name accordingly.**

Also, diamond ([http://www.diamondsearch.org/index.php](http://www.diamondsearch.org/index.php)) search is allowed by '--diamond'. This homology search is similar to the conventional BLAST, and is said to accelerate the search by more than 1000 times but with some cost in accuracy and sensitivity. You can install diamond from its aforementioned web page. **It is recommended to do a rapid test using "--diamond" to ensure iSeeCE.sh correctly runs.**

I also updated the parallelization of the scripts by employing the parallel Ruby package. You may want to use "`gem install parallel`" to install it. In addition, you can do "bash iSeeCE.sh --cpu" to set the number of threads for both BLAST (or diamond) and MAFFT.

Moreover, I have tested the use of Mauve and it is perfectly fine. Please note that the argument is changed to `--mauve --mauve_prog progressiveMauve --mauve_jar Mauve.jar`.

Again, thanks very much for your reporting these bugs and your interest in iSeeCE. Please don't hesitate to let me know should there be further questions on the script or interpretation of the result.

**Comment by evolbeginner** [comment]
Please also see examples provided in the README file for the change in the arguments. In brief, the orthomcl configuration file, where you also need to change the password and login name of MySQL, has to be specified by `bash iSeeCE.sh --orthomcl_config`.

**Comment by alexandergz1983** [comment]
Hello,
Your modifications work perfectly,  thank you very much for your patience and help. One last thing, you forgot to add in iSeeCE.sh: export RUBYLIB = $ RUBYLIB: $ CWD / lib. :)

**Comment by evolbeginner** [comment]
Hi Alex,

So glad to hear that it was successful!

I am thinking that it may still be fine to use Mauve for within-genus analysis, but for across-genus analysis it may not perform well. Actually, in our original paper, many of the CE genes were detected without using Mauve; instead, they were identified by the bestHit method for synteny and by FastTree (initial analysis) + RAxML (confirmation) for phylogenetic evidence, as indicated in Figure 1 (the info of our original paper and database is updated in README).

Thanks.
